add html homepage
xsenikx/WenzelSebastien_3_11032021 pull request #15
Opened 2021-03-16 03:28 UTC by xsenikx

close #3

2021-03-16 07:55 UTC, Tutt-J requested changes

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +    <title>Oh My Food</title>
Mising meta description

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +    <div>
What is this div ?

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <h1>Paris, Belleville</h1>
Not a h1

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <h2>
H1

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +          Réservez le menu qui <br />
Remove br

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +          Découvrir des restaurants d'exception,<br />
Remove br

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +          Découvrir des restaurants d'exception,<br />
Découvrez

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <button>Explorer nos restaurants</button>
Not a button it's a `<a>`

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <div>
Use ol with li, not put number we put it later with css before

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <h2>restaurants</h2>
Missing maj

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +        <div>
Remove div

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +                <i class="fas fa-heart"></i>
Not the same heart two times

2021-03-16 07:55 UTC, Tutt-J commented on index.html
> +                <p>Nouveau</p>
Mus be on figure with img

2021-03-16 10:05 UTC, xsenikx commented on index.html
> +    <div>
it's for my animation "loading-page"

2021-03-19 08:20 UTC, Tutt-J approved these changes

2021-03-19 08:20 UTC, merged